### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by Mr-KayJayDee** [SudhanPlayz/discordjs-activity#12]
Can you explain how we can to that but in two separate line:
- Import the module
- Add the client to the module

require("discordjs-activity")(client)
                             ^
TypeError: require(...) is not a function

Node: v16.6
Npm: v7.30

**Comment by SudhanPlayz** [comment]
You have did it wrong, The code supposed to be look like this and its working fine for me in that version
![image](https://user-images.githubusercontent.com/55418697/130037659-1d533713-a4f7-448a-b33d-539b6caf9d0f.png)
