### ISSUE TITLE
Question: How did you get the application ID for the activities?

### ISSUE THREAD

**Issue by Endy3032** [SudhanPlayz/discordjs-activity#17]
Just wanna know how so I can implement it in my bot when new activities are introduced but not available here yet

**Comment by SudhanPlayz** [comment]
Answer from the games lab server:

> Q: Can I create and release Activities and Games for Discord?
A: We're keeping game development both as an internal effort and with select partners only for now. We'll post here and elsewhere when/if we open the platform up for more content development.
