### ISSUE TITLE
TypeError: VoiceChannel.activityInvite is not a function

### ISSUE THREAD

**Issue by Alexsuper199** [SudhanPlayz/discordjs-activity#21]
hello i was trying to add commands to the bot (i use my command handler). But I get the error:
TypeError: VoiceChannel.activityInvite is not a function
Here is my code (I have Discord.js v13):
```
require("discordjs-activity");

const Command = require("../Structures/Command");

module.exports = new Command({
    name: "activities",
    description: "Voice minigames command",
    cooldown: 10,
    permissions: ["SEND_MESSAGES"],
    async run(message, args, client){
        
        const voice = args[0];
        const game = args[1];

        try {
            if(game === 'youtube'){
                let VoiceChannel = client.channels.cache.get(voice)
                let Invite = await VoiceChannel.activityInvite("youtube_together")
                if(Invite) {
                    message.reply("https://discord.com/invite/"+Invite.code)
                }
            }
        } catch (error) {
            console.log(error)
        }
    }
});
```
How can i fix this?

**Comment by JotaroKujo0525** [comment]
> hello i was trying to add commands to the bot (i use my command handler). But I get the error: TypeError: VoiceChannel.activityInvite is not a function Here is my code (I have Discord.js v13):
> 
> ```
> require("discordjs-activity");
> 
> const Command = require("../Structures/Command");
> 
> module.exports = new Command({
>     name: "activities",
>     description: "Voice minigames command",
>     cooldown: 10,
>     permissions: ["SEND_MESSAGES"],
>     async run(message, args, client){
>         
>         const voice = args[0];
>         const game = args[1];
> 
>         try {
>             if(game === 'youtube'){
>                 let VoiceChannel = client.channels.cache.get(voice)
>                 let Invite = await VoiceChannel.activityInvite("youtube_together")
>                 if(Invite) {
>                     message.reply("https://discord.com/invite/"+Invite.code)
>                 }
>             }
>         } catch (error) {
>             console.log(error)
>         }
>     }
> });
> ```
> 
> How can i fix this?

We don't support djs 13

**Comment by Alexsuper199** [comment]
I hope there will be an update

**Comment by DarrenOfficial** [comment]
> I hope there will be an update

Well the simple way to do it is just to fetch the code yourself, like this for example
https://github.com/SudhanPlayz/Discord-MusicBot/blob/74065d167f6dab66b1910ece7368077c0a4b865c/commands/slash/youtube.js#L29

**Comment by SudhanPlayz** [comment]
You are supposed to require the module before defining client
