### ISSUE TITLE
Can't join multiple players in Fishington and Betrayal

### ISSUE THREAD

**Issue by leoodz** [SudhanPlayz/discordjs-activity#4]
Only one player can join the link the rest of the people can't join the link

![image](https://user-images.githubusercontent.com/26497373/123440857-6f8ebe00-d5fd-11eb-913b-b19003909fbb.png)

**Comment by SudhanPlayz** [comment]
Maybe because of voice channel limit/game limit

**Comment by leoodz** [comment]
> Maybe because of voice channel limit/game limit

I think it was the game cuz the other game like poker and youtube work perfectly fine
